# Auto-generated by nodebpy.assets.generate_asset_api — do not edit manually.
from typing import TYPE_CHECKING
from ...builder import (
    AssetCompositorGroup,
    BooleanSocket,
    BundledLibrary,
    ColorSocket,
    FloatSocket,
    IntegerSocket,
    MatrixSocket,
    MenuSocket,
    ObjectSocket,
    SocketAccessor,
    VectorSocket,
)
from ...types import (
    InputBoolean,
    InputColor,
    InputFloat,
    InputInteger,
    InputMatrix,
    InputMenu,
    InputObject,
    InputVector,
)


class ChromaticAberration(AssetCompositorGroup):
    """Chromatic Aberration"""

    _name = "Chromatic Aberration"
    _asset_name = "Chromatic Aberration"
    _library = BundledLibrary("compositing_nodes_essentials.blend")

    class _Inputs(SocketAccessor):
        image: ColorSocket
        """Image"""
        type: MenuSocket
        """Type"""
        factor: FloatSocket
        """Factor"""

    class _Outputs(SocketAccessor):
        image: ColorSocket
        """Image"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        image: InputColor = None,
        type: InputMenu = "Scale",
        factor: InputFloat = 0.2,
    ):
        super().__init__(**{"Socket_1": image, "Socket_6": type, "Socket_2": factor})


class CombineCylindrical(AssetCompositorGroup):
    """Combine Cylindrical"""

    _name = "Combine Cylindrical"
    _asset_name = "Combine Cylindrical"
    _library = BundledLibrary("compositing_nodes_essentials.blend")

    class _Inputs(SocketAccessor):
        r: FloatSocket
        """R"""
        phi: FloatSocket
        """Phi"""
        z: FloatSocket
        """Z"""

    class _Outputs(SocketAccessor):
        vector: VectorSocket
        """Vector"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        r: InputFloat = 0.0,
        phi: InputFloat = 0.0,
        z: InputFloat = 0.0,
    ):
        super().__init__(**{"Socket_1": r, "Socket_2": phi, "Socket_3": z})


class CombineSpherical(AssetCompositorGroup):
    """Combine Spherical"""

    _name = "Combine Spherical"
    _asset_name = "Combine Spherical"
    _library = BundledLibrary("compositing_nodes_essentials.blend")

    class _Inputs(SocketAccessor):
        r: FloatSocket
        """R"""
        phi: FloatSocket
        """Phi"""
        theta: FloatSocket
        """Theta"""

    class _Outputs(SocketAccessor):
        vector: VectorSocket
        """Vector"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        r: InputFloat = 0.0,
        phi: InputFloat = 0.0,
        theta: InputFloat = 0.0,
    ):
        super().__init__(**{"Socket_1": r, "Socket_2": phi, "Socket_3": theta})


class FilmGrain(AssetCompositorGroup):
    """Simulates the noise and behavior of analog film. Author: Selman Vorhoff"""

    _name = "Film Grain"
    _asset_name = "Film Grain"
    _library = BundledLibrary("compositing_nodes_essentials.blend")

    class _Inputs(SocketAccessor):
        input: ColorSocket
        """Input"""
        factor: FloatSocket
        """Factor"""
        preset: MenuSocket
        """Preset"""
        animated: BooleanSocket
        """Animated"""

    class _Outputs(SocketAccessor):
        result: ColorSocket
        """Result"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        input: InputColor = None,
        factor: InputFloat = 1.0,
        preset: InputMenu = "Super 8 mm",
        animated: InputBoolean = False,
    ):
        super().__init__(
            **{
                "Socket_1": input,
                "Socket_7": factor,
                "Socket_64": preset,
                "Socket_10": animated,
            }
        )


class ProjectWithDepth(AssetCompositorGroup):
    """Project with Depth"""

    _name = "Project with Depth"
    _asset_name = "Project with Depth"
    _library = BundledLibrary("compositing_nodes_essentials.blend")

    class _Inputs(SocketAccessor):
        normalized: VectorSocket
        """Normalized"""
        depth: FloatSocket
        """Depth"""
        projection: MatrixSocket
        """Projection"""
        transform: MatrixSocket
        """Transform"""
        clip_start: FloatSocket
        """Clip Start"""
        clip_end: FloatSocket
        """Clip End"""

    class _Outputs(SocketAccessor):
        vector: VectorSocket
        """Vector"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        normalized: InputVector = None,
        depth: InputFloat = 1.0,
        projection: InputMatrix = None,
        transform: InputMatrix = None,
        clip_start: InputFloat = 0.1,
        clip_end: InputFloat = 100.0,
    ):
        super().__init__(
            **{
                "Socket_3": normalized,
                "Socket_4": depth,
                "Socket_5": projection,
                "Socket_6": transform,
                "Socket_1": clip_start,
                "Socket_2": clip_end,
            }
        )


class Retime(AssetCompositorGroup):
    """Retime"""

    _name = "Retime"
    _asset_name = "Retime"
    _library = BundledLibrary("compositing_nodes_essentials.blend")

    class _Inputs(SocketAccessor):
        offset: IntegerSocket
        """Offset"""
        step: IntegerSocket
        """Step"""
        speed: FloatSocket
        """Speed"""
        cyclic: BooleanSocket
        """Cyclic"""

    class _Outputs(SocketAccessor):
        frame: IntegerSocket
        """Frame"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        offset: InputInteger = 0,
        step: InputInteger = 1,
        speed: InputFloat = 1.0,
        cyclic: InputBoolean = False,
    ):
        super().__init__(
            **{
                "Socket_4": offset,
                "Socket_13": step,
                "Socket_14": speed,
                "Socket_11": cyclic,
            }
        )


class ScreenTo3DSpace(AssetCompositorGroup):
    """Convert coordinates from screen to world space"""

    _name = "Screen to 3D Space"
    _asset_name = "Screen to 3D Space"
    _library = BundledLibrary("compositing_nodes_essentials.blend")

    class _Inputs(SocketAccessor):
        normalized: VectorSocket
        """Normalized"""
        depth: FloatSocket
        """Depth"""
        camera: ObjectSocket
        """Camera"""

    class _Outputs(SocketAccessor):
        vector: VectorSocket
        """Vector"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        normalized: InputVector = None,
        depth: InputFloat = 0.0,
        camera: InputObject = None,
    ):
        super().__init__(
            **{"Socket_0": normalized, "Socket_3": depth, "Socket_1": camera}
        )


class SensorNoise(AssetCompositorGroup):
    """Sensor Noise"""

    _name = "Sensor Noise"
    _asset_name = "Sensor Noise"
    _library = BundledLibrary("compositing_nodes_essentials.blend")

    class _Inputs(SocketAccessor):
        image: ColorSocket
        """Image"""
        luminance_noise: FloatSocket
        """Luminance Noise"""
        chroma_noise: FloatSocket
        """Chroma Noise"""
        animated: BooleanSocket
        """Animated"""

    class _Outputs(SocketAccessor):
        image: ColorSocket
        """Image"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        image: InputColor = None,
        luminance_noise: InputFloat = 0.1,
        chroma_noise: InputFloat = 0.05,
        animated: InputBoolean = False,
    ):
        super().__init__(
            **{
                "Socket_1": image,
                "Socket_2": luminance_noise,
                "Socket_4": chroma_noise,
                "Socket_3": animated,
            }
        )


class SeparateCylindrical(AssetCompositorGroup):
    """Decompose into its cylindrical components"""

    _name = "Separate Cylindrical"
    _asset_name = "Separate Cylindrical"
    _library = BundledLibrary("compositing_nodes_essentials.blend")

    class _Inputs(SocketAccessor):
        vector: VectorSocket
        """Vector"""

    class _Outputs(SocketAccessor):
        r: FloatSocket
        """R"""
        phi: FloatSocket
        """Phi"""
        z: FloatSocket
        """Z"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        vector: InputVector = None,
    ):
        super().__init__(**{"Socket_0": vector})


class SeparateSpherical(AssetCompositorGroup):
    """Decompose into its cylindrical components"""

    _name = "Separate Spherical"
    _asset_name = "Separate Spherical"
    _library = BundledLibrary("compositing_nodes_essentials.blend")

    class _Inputs(SocketAccessor):
        vector: VectorSocket
        """Vector"""

    class _Outputs(SocketAccessor):
        r: FloatSocket
        """R"""
        phi: FloatSocket
        """Phi"""
        theta: FloatSocket
        """Theta"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        vector: InputVector = None,
    ):
        super().__init__(**{"Socket_0": vector})


class Sepia(AssetCompositorGroup):
    """Sepia"""

    _name = "Sepia"
    _asset_name = "Sepia"
    _library = BundledLibrary("compositing_nodes_essentials.blend")

    class _Inputs(SocketAccessor):
        image: ColorSocket
        """Image"""
        contrast: FloatSocket
        """Contrast"""
        tone: FloatSocket
        """Tone"""
        saturation: FloatSocket
        """Saturation"""

    class _Outputs(SocketAccessor):
        image: ColorSocket
        """Image"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        image: InputColor = None,
        contrast: InputFloat = 0.0,
        tone: InputFloat = 0.5,
        saturation: InputFloat = 1.0,
    ):
        super().__init__(
            **{
                "Socket_1": image,
                "Socket_9": contrast,
                "Socket_6": tone,
                "Socket_7": saturation,
            }
        )


class SplitToning(AssetCompositorGroup):
    """Split Toning"""

    _name = "Split Toning"
    _asset_name = "Split Toning"
    _library = BundledLibrary("compositing_nodes_essentials.blend")

    class _Inputs(SocketAccessor):
        image: ColorSocket
        """Image"""
        highlights: ColorSocket
        """Highlights"""
        factor_highlights: FloatSocket
        """Factor Highlights"""
        shadows: ColorSocket
        """Shadows"""
        factor_shadows: FloatSocket
        """Factor Shadows"""
        balance: FloatSocket
        """Balance"""
        smoothness: FloatSocket
        """Smoothness"""

    class _Outputs(SocketAccessor):
        image: ColorSocket
        """Image"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        image: InputColor = None,
        highlights: InputColor = None,
        factor_highlights: InputFloat = 0.5,
        shadows: InputColor = None,
        factor_shadows: InputFloat = 0.2,
        balance: InputFloat = 0.2,
        smoothness: InputFloat = 0.4,
    ):
        super().__init__(
            **{
                "Socket_1": image,
                "Socket_5": highlights,
                "Socket_4": factor_highlights,
                "Socket_6": shadows,
                "Socket_7": factor_shadows,
                "Socket_2": balance,
                "Socket_3": smoothness,
            }
        )


class TransformAndProject(AssetCompositorGroup):
    """Transform and Project"""

    _name = "Transform and Project"
    _asset_name = "Transform and Project"
    _library = BundledLibrary("compositing_nodes_essentials.blend")

    class _Inputs(SocketAccessor):
        vector: VectorSocket
        """Vector"""
        transform: MatrixSocket
        """Transform"""
        projection: MatrixSocket
        """Projection"""

    class _Outputs(SocketAccessor):
        normalized: VectorSocket
        """Normalized"""
        depth: FloatSocket
        """Depth"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        vector: InputVector = None,
        transform: InputMatrix = None,
        projection: InputMatrix = None,
    ):
        super().__init__(
            **{"Socket_3": vector, "Socket_0": transform, "Socket_1": projection}
        )


class TuneImage(AssetCompositorGroup):
    """Tune Image"""

    _name = "Tune Image"
    _asset_name = "Tune Image"
    _library = BundledLibrary("compositing_nodes_essentials.blend")

    class _Inputs(SocketAccessor):
        image: ColorSocket
        """Image"""
        contrast: FloatSocket
        """Contrast"""
        color_boost: FloatSocket
        """Color Boost"""
        clarity: FloatSocket
        """Clarity"""
        detail: FloatSocket
        """Detail"""
        sharpen: FloatSocket
        """Sharpen"""
        preserve_colors: BooleanSocket
        """Preserve Colors"""

    class _Outputs(SocketAccessor):
        image: ColorSocket
        """Image"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        image: InputColor = None,
        contrast: InputFloat = 0.0,
        color_boost: InputFloat = 0.0,
        clarity: InputFloat = 0.0,
        detail: InputFloat = 0.0,
        sharpen: InputFloat = 0.0,
        preserve_colors: InputBoolean = True,
    ):
        super().__init__(
            **{
                "Socket_0": image,
                "Socket_5": contrast,
                "Socket_2": color_boost,
                "Socket_3": clarity,
                "Socket_4": detail,
                "Socket_7": sharpen,
                "Socket_6": preserve_colors,
            }
        )


class UnsharpMask(AssetCompositorGroup):
    """Unsharp Mask"""

    _name = "Unsharp Mask"
    _asset_name = "Unsharp Mask"
    _library = BundledLibrary("compositing_nodes_essentials.blend")

    class _Inputs(SocketAccessor):
        image: ColorSocket
        """Image"""
        radius: FloatSocket
        """Radius"""
        factor: FloatSocket
        """Factor"""
        threshold: FloatSocket
        """Threshold"""

    class _Outputs(SocketAccessor):
        result: ColorSocket
        """Result"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        image: InputColor = None,
        radius: InputFloat = 8.0,
        factor: InputFloat = 0.5,
        threshold: InputFloat = 0.0,
    ):
        super().__init__(
            **{
                "Socket_1": image,
                "Socket_2": radius,
                "Socket_3": factor,
                "Socket_4": threshold,
            }
        )


class Vignette(AssetCompositorGroup):
    """Vignette"""

    _name = "Vignette"
    _asset_name = "Vignette"
    _library = BundledLibrary("compositing_nodes_essentials.blend")

    class _Inputs(SocketAccessor):
        image: ColorSocket
        """Image"""
        factor: FloatSocket
        """Factor"""
        feather: FloatSocket
        """Feather"""
        corner_roundness: FloatSocket
        """Corner Roundness"""
        scale: VectorSocket
        """Scale"""
        offset: VectorSocket
        """Offset"""
        angle: FloatSocket
        """Angle"""

    class _Outputs(SocketAccessor):
        image: ColorSocket
        """Image"""
        mask: FloatSocket
        """Mask"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        image: InputColor = None,
        factor: InputFloat = 1.0,
        feather: InputFloat = 0.4,
        corner_roundness: InputFloat = 1.0,
        scale: InputVector = None,
        offset: InputVector = None,
        angle: InputFloat = 0.0,
    ):
        super().__init__(
            **{
                "Socket_1": image,
                "Socket_10": factor,
                "Socket_4": feather,
                "Socket_3": corner_roundness,
                "Socket_8": scale,
                "Socket_6": offset,
                "Socket_7": angle,
            }
        )


class _3DToScreenSpace(AssetCompositorGroup):
    """Convert input coordinates to normalized camera space"""

    _name = "3D to Screen Space"
    _asset_name = "3D to Screen Space"
    _library = BundledLibrary("compositing_nodes_essentials.blend")

    class _Inputs(SocketAccessor):
        vector: VectorSocket
        """Vector"""
        camera: ObjectSocket
        """Camera"""
        clamp_depth: BooleanSocket
        """Clamp Depth"""

    class _Outputs(SocketAccessor):
        normalized: VectorSocket
        """Normalized"""
        depth: FloatSocket
        """Depth"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        vector: InputVector = None,
        camera: InputObject = None,
        clamp_depth: InputBoolean = True,
    ):
        super().__init__(
            **{"Socket_4": vector, "Socket_0": camera, "Socket_6": clamp_depth}
        )


__all__ = (
    "ChromaticAberration",
    "CombineCylindrical",
    "CombineSpherical",
    "FilmGrain",
    "ProjectWithDepth",
    "Retime",
    "ScreenTo3DSpace",
    "SensorNoise",
    "SeparateCylindrical",
    "SeparateSpherical",
    "Sepia",
    "SplitToning",
    "TransformAndProject",
    "TuneImage",
    "UnsharpMask",
    "Vignette",
    "_3DToScreenSpace",
)
