# Auto-generated by nodebpy.assets.generate_asset_api — do not edit manually.
from typing import TYPE_CHECKING
from ...builder import (
    AssetShaderGroup,
    BundledLibrary,
    FloatSocket,
    SocketAccessor,
    VectorSocket,
)
from ...types import (
    InputFloat,
    InputVector,
)


class CombineCylindrical(AssetShaderGroup):
    """Combine Cylindrical"""

    _name = "Combine Cylindrical"
    _asset_name = "Combine Cylindrical"
    _library = BundledLibrary("shading_nodes_essentials.blend")

    class _Inputs(SocketAccessor):
        r: FloatSocket
        """R"""
        phi: FloatSocket
        """Phi"""
        z: FloatSocket
        """Z"""

    class _Outputs(SocketAccessor):
        vector: VectorSocket
        """Vector"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        r: InputFloat = 0.0,
        phi: InputFloat = 0.0,
        z: InputFloat = 0.0,
    ):
        super().__init__(**{"Socket_1": r, "Socket_2": phi, "Socket_3": z})


class CombineSpherical(AssetShaderGroup):
    """Combine Spherical"""

    _name = "Combine Spherical"
    _asset_name = "Combine Spherical"
    _library = BundledLibrary("shading_nodes_essentials.blend")

    class _Inputs(SocketAccessor):
        r: FloatSocket
        """R"""
        phi: FloatSocket
        """Phi"""
        theta: FloatSocket
        """Theta"""

    class _Outputs(SocketAccessor):
        vector: VectorSocket
        """Vector"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        r: InputFloat = 0.0,
        phi: InputFloat = 0.0,
        theta: InputFloat = 0.0,
    ):
        super().__init__(**{"Socket_1": r, "Socket_2": phi, "Socket_3": theta})


class SeparateCylindrical(AssetShaderGroup):
    """Separate Cylindrical"""

    _name = "Separate Cylindrical"
    _asset_name = "Separate Cylindrical"
    _library = BundledLibrary("shading_nodes_essentials.blend")

    class _Inputs(SocketAccessor):
        vector: VectorSocket
        """Vector"""

    class _Outputs(SocketAccessor):
        r: FloatSocket
        """R"""
        phi: FloatSocket
        """Phi"""
        z: FloatSocket
        """Z"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        vector: InputVector = None,
    ):
        super().__init__(**{"Socket_0": vector})


class SeparateSpherical(AssetShaderGroup):
    """Separate Spherical"""

    _name = "Separate Spherical"
    _asset_name = "Separate Spherical"
    _library = BundledLibrary("shading_nodes_essentials.blend")

    class _Inputs(SocketAccessor):
        vector: VectorSocket
        """Vector"""

    class _Outputs(SocketAccessor):
        r: FloatSocket
        """R"""
        phi: FloatSocket
        """Phi"""
        theta: FloatSocket
        """Theta"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        vector: InputVector = None,
    ):
        super().__init__(**{"Socket_0": vector})


__all__ = (
    "CombineCylindrical",
    "CombineSpherical",
    "SeparateCylindrical",
    "SeparateSpherical",
)
