# Auto-generated by nodebpy.assets.generate_asset_api — do not edit manually.
from typing import TYPE_CHECKING
from ...builder import (
    AssetGeometryGroup,
    BooleanSocket,
    BundleSocket,
    BundledLibrary,
    ClosureSocket,
    CollectionSocket,
    FloatSocket,
    GeometrySocket,
    ImageSocket,
    IntegerSocket,
    MaterialSocket,
    MatrixSocket,
    MenuSocket,
    ObjectSocket,
    RotationSocket,
    SocketAccessor,
    StringSocket,
    VectorSocket,
)
from ...types import (
    InputBoolean,
    InputBundle,
    InputClosure,
    InputCollection,
    InputFloat,
    InputGeometry,
    InputImage,
    InputInteger,
    InputMaterial,
    InputMatrix,
    InputMenu,
    InputObject,
    InputRotation,
    InputString,
    InputVector,
)


class Array(AssetGeometryGroup):
    """Array"""

    _name = "Array"
    _asset_name = "Array"
    _library = BundledLibrary("geometry_nodes_essentials.blend")

    class _Inputs(SocketAccessor):
        geometry: GeometrySocket
        """Geometry"""
        shape: MenuSocket
        """Shape"""
        count: IntegerSocket
        """Count"""
        offset_method: MenuSocket
        """Offset Method"""
        offset: VectorSocket
        """Offset"""
        rotation: RotationSocket
        """Rotation"""
        scale: VectorSocket
        """Scale"""
        realize_instances: BooleanSocket
        """Realize Instances"""
        randomize: BooleanSocket
        """Randomize"""
        seed: IntegerSocket
        """Seed"""
        merge: BooleanSocket
        """Merge"""

    class _Outputs(SocketAccessor):
        geometry: GeometrySocket
        """Geometry"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        geometry: InputGeometry = None,
        shape: InputMenu = "Line",
        count: InputInteger = 3,
        offset_method: InputMenu = "Relative",
        offset: InputVector = None,
        rotation: InputRotation = None,
        scale: InputVector = None,
        realize_instances: InputBoolean = True,
        randomize: InputBoolean = False,
        seed: InputInteger = 0,
        merge: InputBoolean = False,
    ):
        super().__init__(
            **{
                "Socket_7": geometry,
                "Socket_2": shape,
                "Socket_5": count,
                "Socket_14": offset_method,
                "Socket_21": offset,
                "Socket_9": rotation,
                "Socket_10": scale,
                "Socket_38": realize_instances,
                "Socket_17": randomize,
                "Socket_18": seed,
                "Socket_31": merge,
            }
        )


class AttachHairCurvesToSurface(AssetGeometryGroup):
    """Attach Hair Curves to Surface"""

    _name = "Attach Hair Curves to Surface"
    _asset_name = "Attach Hair Curves to Surface"
    _library = BundledLibrary("procedural_hair_node_assets.blend")

    class _Inputs(SocketAccessor):
        geometry: GeometrySocket
        """Geometry"""
        surface_source: MenuSocket
        """Surface Source"""
        surface_object: ObjectSocket
        """Surface Object"""
        surface_uv_map: VectorSocket
        """Surface UV Map"""
        resting_surface: BooleanSocket
        """Resting Surface"""
        use_existing_attachment: BooleanSocket
        """Use Existing Attachment"""
        snap_to_surface: BooleanSocket
        """Snap to Surface"""
        blend_along_curve: FloatSocket
        """Blend along Curve"""
        align_to_surface_normal: BooleanSocket
        """Align to Surface Normal"""

    class _Outputs(SocketAccessor):
        geometry: GeometrySocket
        """Geometry"""
        surface_uv_coordinate: VectorSocket
        """Surface UV Coordinate"""
        surface_normal: VectorSocket
        """Surface Normal"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        geometry: InputGeometry = None,
        surface_source: InputMenu = "Object",
        surface_object: InputObject = None,
        surface_uv_map: InputVector = None,
        resting_surface: InputBoolean = False,
        use_existing_attachment: InputBoolean = False,
        snap_to_surface: InputBoolean = True,
        blend_along_curve: InputFloat = 0.0,
        align_to_surface_normal: InputBoolean = False,
    ):
        super().__init__(
            **{
                "Input_0": geometry,
                "Socket_2": surface_source,
                "Input_4": surface_object,
                "Input_2": surface_uv_map,
                "Input_6": resting_surface,
                "Input_10": use_existing_attachment,
                "Input_8": snap_to_surface,
                "Input_12": blend_along_curve,
                "Input_7": align_to_surface_normal,
            }
        )


class AttachmentInfo(AssetGeometryGroup):
    """Attachment Info"""

    _name = "Attachment Info"
    _asset_name = "Attachment Info"
    _library = BundledLibrary("procedural_hair_node_assets.blend")

    class _Inputs(SocketAccessor):
        hair_curves: GeometrySocket
        """Hair Curves"""

    class _Outputs(SocketAccessor):
        surface_geometry: GeometrySocket
        """Surface Geometry"""
        surface_exists: BooleanSocket
        """Surface Exists"""
        attachment_uv: VectorSocket
        """Attachment UV"""
        attachment_is_valid: BooleanSocket
        """Attachment is Valid"""
        surface_normal: VectorSocket
        """Surface Normal"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        hair_curves: InputGeometry = None,
    ):
        super().__init__(**{"Input_8": hair_curves})


class BlendHairCurves(AssetGeometryGroup):
    """Blend Hair Curves"""

    _name = "Blend Hair Curves"
    _asset_name = "Blend Hair Curves"
    _library = BundledLibrary("procedural_hair_node_assets.blend")

    class _Inputs(SocketAccessor):
        geometry: GeometrySocket
        """Geometry"""
        factor: FloatSocket
        """Factor"""
        blend_radius: FloatSocket
        """Blend Radius"""
        blend_neighbors: IntegerSocket
        """Blend Neighbors"""
        preserve_length: BooleanSocket
        """Preserve Length"""

    class _Outputs(SocketAccessor):
        geometry: GeometrySocket
        """Geometry"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        geometry: InputGeometry = None,
        factor: InputFloat = 1.0,
        blend_radius: InputFloat = 0.05,
        blend_neighbors: InputInteger = 10,
        preserve_length: InputBoolean = False,
    ):
        super().__init__(
            **{
                "Input_0": geometry,
                "Input_2": factor,
                "Input_5": blend_radius,
                "Input_4": blend_neighbors,
                "Input_6": preserve_length,
            }
        )


class BoxSelection(AssetGeometryGroup):
    """Box Selection"""

    _name = "Box Selection"
    _asset_name = "Box Selection"
    _library = BundledLibrary("geometry_nodes_essentials.blend")

    class _Inputs(SocketAccessor):
        center: VectorSocket
        """Center"""
        size: VectorSocket
        """Size"""

    class _Outputs(SocketAccessor):
        selection: BooleanSocket
        """Selection"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        center: InputVector = None,
        size: InputVector = None,
    ):
        super().__init__(**{"Socket_1": center, "Socket_2": size})


class BraidHairCurves(AssetGeometryGroup):
    """Braid Hair Curves"""

    _name = "Braid Hair Curves"
    _asset_name = "Braid Hair Curves"
    _library = BundledLibrary("procedural_hair_node_assets.blend")

    class _Inputs(SocketAccessor):
        geometry: GeometrySocket
        """Geometry"""
        factor: FloatSocket
        """Factor"""
        subdivision: IntegerSocket
        """Subdivision"""
        braid_start: FloatSocket
        """Braid Start"""
        radius: FloatSocket
        """Radius"""
        shape: FloatSocket
        """Shape"""
        frequency: FloatSocket
        """Frequency"""
        factor_min: FloatSocket
        """Factor Min"""
        factor_max: FloatSocket
        """Factor Max"""
        thickness: FloatSocket
        """Thickness"""
        thickness_shape: FloatSocket
        """Thickness Shape"""
        shape_asymmetry: FloatSocket
        """Shape Asymmetry"""
        flare_length: FloatSocket
        """Flare Length"""
        flare_opening: FloatSocket
        """Flare Opening"""
        hair_tie: BooleanSocket
        """Hair Tie"""
        guide_index: IntegerSocket
        """Guide Index"""
        guide_distance: FloatSocket
        """Guide Distance"""
        guide_mask: FloatSocket
        """Guide Mask"""
        existing_guide_map: BooleanSocket
        """Existing Guide Map"""

    class _Outputs(SocketAccessor):
        geometry: GeometrySocket
        """Geometry"""
        flare_parameter: FloatSocket
        """Flare Parameter"""
        strand_index: IntegerSocket
        """Strand Index"""
        guide_index: IntegerSocket
        """Guide Index"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        geometry: InputGeometry = None,
        factor: InputFloat = 1.0,
        subdivision: InputInteger = 1,
        braid_start: InputFloat = 0.1,
        radius: InputFloat = 0.1,
        shape: InputFloat = 0.5,
        frequency: InputFloat = 1.0,
        factor_min: InputFloat = 0.0,
        factor_max: InputFloat = 1.0,
        thickness: InputFloat = 1.0,
        thickness_shape: InputFloat = 0.5,
        shape_asymmetry: InputFloat = 0.0,
        flare_length: InputFloat = 0.0,
        flare_opening: InputFloat = 0.0,
        hair_tie: InputBoolean = False,
        guide_index: InputInteger = -987654,
        guide_distance: InputFloat = 0.1,
        guide_mask: InputFloat = 1.0,
        existing_guide_map: InputBoolean = True,
    ):
        super().__init__(
            **{
                "Input_0": geometry,
                "Input_2": factor,
                "Input_5": subdivision,
                "Input_6": braid_start,
                "Input_7": radius,
                "Input_8": shape,
                "Input_11": frequency,
                "Input_9": factor_min,
                "Input_10": factor_max,
                "Input_14": thickness,
                "Input_13": thickness_shape,
                "Input_12": shape_asymmetry,
                "Input_15": flare_length,
                "Input_21": flare_opening,
                "Socket_2": hair_tie,
                "Input_25": guide_index,
                "Input_4": guide_distance,
                "Input_22": guide_mask,
                "Input_3": existing_guide_map,
            }
        )


class CaptureRestGeometry(AssetGeometryGroup):
    """Capture Rest Geometry"""

    _name = "Capture Rest Geometry"
    _asset_name = "Capture Rest Geometry"
    _library = BundledLibrary("geometry_nodes_essentials.blend")

    class _Inputs(SocketAccessor):
        geometry: GeometrySocket
        """Geometry"""
        rest_position: BooleanSocket
        """Rest Position"""

    class _Outputs(SocketAccessor):
        geometry: GeometrySocket
        """Geometry"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        geometry: InputGeometry = None,
        rest_position: InputBoolean = True,
    ):
        super().__init__(**{"Socket_1": geometry, "Socket_2": rest_position})


class ClothDynamicsExperimental(AssetGeometryGroup):
    """Simulate cloth while taking into account effectors like colliders and forces."""

    _name = "Cloth Dynamics (Experimental)"
    _asset_name = "Cloth Dynamics (Experimental)"
    _library = BundledLibrary("geometry_nodes_dynamics_assets.blend")

    class _Inputs(SocketAccessor):
        geometry: GeometrySocket
        """Geometry"""
        pin_group: FloatSocket
        """Pin Group"""
        invert_pin_group: BooleanSocket
        """Invert Pin Group"""
        stretchiness: FloatSocket
        """Stretchiness"""
        bendiness: FloatSocket
        """Bendiness"""
        substeps: IntegerSocket
        """Substeps"""
        constraint_steps: IntegerSocket
        """Constraint Steps"""
        simulation_to_world: MatrixSocket
        """Simulation to World"""
        mass: FloatSocket
        """Mass"""
        friction: FloatSocket
        """Friction"""
        collision_radius: FloatSocket
        """Collision Radius"""
        linear_damping: FloatSocket
        """Linear Damping"""
        socket_5: BooleanSocket
        """Gravity"""
        socket_3: VectorSocket
        """Gravity"""
        tearing: BooleanSocket
        """Tearing"""
        effectors_collection: CollectionSocket
        """Effectors Collection"""
        cloth_tags: StringSocket
        """Cloth Tags"""
        extra_sim_attributes: StringSocket
        """Extra Sim Attributes"""
        effectors: BundleSocket
        """Effectors"""

    class _Outputs(SocketAccessor):
        geometry: GeometrySocket
        """Geometry"""
        residual_error: FloatSocket
        """Residual Error"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        geometry: InputGeometry = None,
        pin_group: InputFloat = 0.0,
        invert_pin_group: InputBoolean = False,
        stretchiness: InputFloat = 0.0,
        bendiness: InputFloat = 0.0,
        substeps: InputInteger = 5,
        constraint_steps: InputInteger = 15,
        simulation_to_world: InputMatrix = None,
        mass: InputFloat = 1.0,
        friction: InputFloat = 0.5,
        collision_radius: InputFloat = 0.01,
        linear_damping: InputFloat = 1.0,
        socket_5: InputBoolean = True,
        socket_3: InputVector = None,
        tearing: InputBoolean = False,
        effectors_collection: InputCollection = None,
        cloth_tags: InputString = "",
        extra_sim_attributes: InputString = "",
        effectors: InputBundle = None,
    ):
        super().__init__(
            **{
                "Socket_0": geometry,
                "Socket_2": pin_group,
                "Socket_23": invert_pin_group,
                "Socket_6": stretchiness,
                "Socket_30": bendiness,
                "Socket_14": substeps,
                "Socket_15": constraint_steps,
                "Socket_29": simulation_to_world,
                "Socket_31": mass,
                "Socket_28": friction,
                "Socket_24": collision_radius,
                "Socket_8": linear_damping,
                "Socket_5": socket_5,
                "Socket_3": socket_3,
                "Socket_11": tearing,
                "Socket_7": effectors_collection,
                "Socket_20": cloth_tags,
                "Socket_22": extra_sim_attributes,
                "Socket_21": effectors,
            }
        )


class ClumpHairCurves(AssetGeometryGroup):
    """Clump Hair Curves"""

    _name = "Clump Hair Curves"
    _asset_name = "Clump Hair Curves"
    _library = BundledLibrary("procedural_hair_node_assets.blend")

    class _Inputs(SocketAccessor):
        geometry: GeometrySocket
        """Geometry"""
        factor: FloatSocket
        """Factor"""
        shape: FloatSocket
        """Shape"""
        tip_spread: FloatSocket
        """Tip Spread"""
        clump_offset: FloatSocket
        """Clump Offset"""
        distance_falloff: FloatSocket
        """Distance Falloff"""
        distance_threshold: FloatSocket
        """Distance Threshold"""
        preserve_length: BooleanSocket
        """Preserve Length"""
        guide_index: IntegerSocket
        """Guide Index"""
        guide_distance: FloatSocket
        """Guide Distance"""
        guide_mask: FloatSocket
        """Guide Mask"""
        existing_guide_map: BooleanSocket
        """Existing Guide Map"""

    class _Outputs(SocketAccessor):
        geometry: GeometrySocket
        """Geometry"""
        guide_index: IntegerSocket
        """Guide Index"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        geometry: InputGeometry = None,
        factor: InputFloat = 1.0,
        shape: InputFloat = 0.5,
        tip_spread: InputFloat = 0.0,
        clump_offset: InputFloat = 0.0,
        distance_falloff: InputFloat = 0.0,
        distance_threshold: InputFloat = 0.0,
        preserve_length: InputBoolean = False,
        guide_index: InputInteger = -987654,
        guide_distance: InputFloat = 0.1,
        guide_mask: InputFloat = 1.0,
        existing_guide_map: InputBoolean = True,
    ):
        super().__init__(
            **{
                "Input_0": geometry,
                "Input_7": factor,
                "Input_6": shape,
                "Input_10": tip_spread,
                "Input_13": clump_offset,
                "Input_12": distance_falloff,
                "Input_11": distance_threshold,
                "Input_15": preserve_length,
                "Input_16": guide_index,
                "Input_9": guide_distance,
                "Input_19": guide_mask,
                "Input_8": existing_guide_map,
            }
        )


class Collider(AssetGeometryGroup):
    """Turn a geometry into a collider."""

    _name = "Collider"
    _asset_name = "Collider"
    _library = BundledLibrary("geometry_nodes_dynamics_assets.blend")

    class _Inputs(SocketAccessor):
        geometry: GeometrySocket
        """Geometry"""
        deforming: BooleanSocket
        """Deforming"""
        boundary: BooleanSocket
        """Boundary"""
        edge_contacts: BooleanSocket
        """Edge Contacts"""
        margin: FloatSocket
        """Margin"""
        friction: FloatSocket
        """Friction"""
        softness: FloatSocket
        """Softness"""
        filter: StringSocket
        """Filter"""
        error_threshold: FloatSocket
        """Error Threshold"""

    class _Outputs(SocketAccessor):
        geometry: GeometrySocket
        """Geometry"""
        collider: BundleSocket
        """Collider"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        geometry: InputGeometry = None,
        deforming: InputBoolean = False,
        boundary: InputBoolean = False,
        edge_contacts: InputBoolean = False,
        margin: InputFloat = 0.0,
        friction: InputFloat = 0.2,
        softness: InputFloat = 0.0,
        filter: InputString = "",
        error_threshold: InputFloat = 0.001,
    ):
        super().__init__(
            **{
                "Socket_0": geometry,
                "Socket_3": deforming,
                "Socket_6": boundary,
                "Socket_5": edge_contacts,
                "Socket_12": margin,
                "Socket_2": friction,
                "Socket_8": softness,
                "Socket_4": filter,
                "Socket_10": error_threshold,
            }
        )


class CombineCylindrical(AssetGeometryGroup):
    """Combine Cylindrical"""

    _name = "Combine Cylindrical"
    _asset_name = "Combine Cylindrical"
    _library = BundledLibrary("geometry_nodes_essentials.blend")

    class _Inputs(SocketAccessor):
        r: FloatSocket
        """R"""
        phi: FloatSocket
        """Phi"""
        z: FloatSocket
        """Z"""

    class _Outputs(SocketAccessor):
        vector: VectorSocket
        """Vector"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        r: InputFloat = 0.0,
        phi: InputFloat = 0.0,
        z: InputFloat = 0.0,
    ):
        super().__init__(**{"Input_3": r, "Input_0": phi, "Socket_2": z})


class CombineSpherical(AssetGeometryGroup):
    """Combine Spherical"""

    _name = "Combine Spherical"
    _asset_name = "Combine Spherical"
    _library = BundledLibrary("geometry_nodes_essentials.blend")

    class _Inputs(SocketAccessor):
        r: FloatSocket
        """R"""
        phi: FloatSocket
        """Phi"""
        theta: FloatSocket
        """Theta"""

    class _Outputs(SocketAccessor):
        vector: VectorSocket
        """Vector"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        r: InputFloat = 0.0,
        phi: InputFloat = 0.0,
        theta: InputFloat = 0.0,
    ):
        super().__init__(**{"Input_3": r, "Input_0": phi, "Input_1": theta})


class CreateGuideIndexMap(AssetGeometryGroup):
    """Create Guide Index Map"""

    _name = "Create Guide Index Map"
    _asset_name = "Create Guide Index Map"
    _library = BundledLibrary("procedural_hair_node_assets.blend")

    class _Inputs(SocketAccessor):
        geometry: GeometrySocket
        """Geometry"""
        guides: GeometrySocket
        """Guides"""
        guide_distance: FloatSocket
        """Guide Distance"""
        guide_mask: FloatSocket
        """Guide Mask"""
        group_id: IntegerSocket
        """Group ID"""

    class _Outputs(SocketAccessor):
        geometry: GeometrySocket
        """Geometry"""
        guide_curves: GeometrySocket
        """Guide Curves"""
        guide_index: IntegerSocket
        """Guide Index"""
        guide_selection: BooleanSocket
        """Guide Selection"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        geometry: InputGeometry = None,
        guides: InputGeometry = None,
        guide_distance: InputFloat = 0.0,
        guide_mask: InputFloat = 1.0,
        group_id: InputInteger = 0,
    ):
        super().__init__(
            **{
                "Input_0": geometry,
                "Input_10": guides,
                "Input_3": guide_distance,
                "Input_11": guide_mask,
                "Input_12": group_id,
            }
        )


class CurlHairCurves(AssetGeometryGroup):
    """Curl Hair Curves"""

    _name = "Curl Hair Curves"
    _asset_name = "Curl Hair Curves"
    _library = BundledLibrary("procedural_hair_node_assets.blend")

    class _Inputs(SocketAccessor):
        geometry: GeometrySocket
        """Geometry"""
        factor: FloatSocket
        """Factor"""
        subdivision: IntegerSocket
        """Subdivision"""
        curl_start: FloatSocket
        """Curl Start"""
        radius: FloatSocket
        """Radius"""
        factor_start: FloatSocket
        """Factor Start"""
        factor_end: FloatSocket
        """Factor End"""
        frequency: FloatSocket
        """Frequency"""
        random_offset: FloatSocket
        """Random Offset"""
        seed: IntegerSocket
        """Seed"""
        guide_index: IntegerSocket
        """Guide Index"""
        guide_distance: FloatSocket
        """Guide Distance"""
        guide_mask: FloatSocket
        """Guide Mask"""
        existing_guide_map: BooleanSocket
        """Existing Guide Map"""

    class _Outputs(SocketAccessor):
        geometry: GeometrySocket
        """Geometry"""
        guide_index: IntegerSocket
        """Guide Index"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        geometry: InputGeometry = None,
        factor: InputFloat = 1.0,
        subdivision: InputInteger = 1,
        curl_start: InputFloat = 0.1,
        radius: InputFloat = 0.1,
        factor_start: InputFloat = 1.0,
        factor_end: InputFloat = 1.0,
        frequency: InputFloat = 1.0,
        random_offset: InputFloat = 0.25,
        seed: InputInteger = 0,
        guide_index: InputInteger = -987654,
        guide_distance: InputFloat = 0.1,
        guide_mask: InputFloat = 1.0,
        existing_guide_map: InputBoolean = True,
    ):
        super().__init__(
            **{
                "Input_0": geometry,
                "Input_2": factor,
                "Input_5": subdivision,
                "Input_6": curl_start,
                "Input_7": radius,
                "Input_9": factor_start,
                "Input_10": factor_end,
                "Input_11": frequency,
                "Input_16": random_offset,
                "Input_15": seed,
                "Input_19": guide_index,
                "Input_4": guide_distance,
                "Input_18": guide_mask,
                "Input_3": existing_guide_map,
            }
        )


class CurveInfo(AssetGeometryGroup):
    """Curve Info"""

    _name = "Curve Info"
    _asset_name = "Curve Info"
    _library = BundledLibrary("procedural_hair_node_assets.blend")

    class _Inputs(SocketAccessor):
        pass

    class _Outputs(SocketAccessor):
        curve_index: IntegerSocket
        """Curve Index"""
        curve_id: IntegerSocket
        """Curve ID"""
        length: FloatSocket
        """Length"""
        direction: VectorSocket
        """Direction"""
        random: FloatSocket
        """Random"""
        surface_uv: VectorSocket
        """Surface UV"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(self):
        super().__init__(**{})


class CurveRoot(AssetGeometryGroup):
    """Curve Root"""

    _name = "Curve Root"
    _asset_name = "Curve Root"
    _library = BundledLibrary("procedural_hair_node_assets.blend")

    class _Inputs(SocketAccessor):
        pass

    class _Outputs(SocketAccessor):
        root_selection: BooleanSocket
        """Root Selection"""
        root_position: VectorSocket
        """Root Position"""
        root_direction: VectorSocket
        """Root Direction"""
        root_index: IntegerSocket
        """Root Index"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(self):
        super().__init__(**{})


class CurveSegment(AssetGeometryGroup):
    """Curve Segment"""

    _name = "Curve Segment"
    _asset_name = "Curve Segment"
    _library = BundledLibrary("procedural_hair_node_assets.blend")

    class _Inputs(SocketAccessor):
        pass

    class _Outputs(SocketAccessor):
        segment_length: FloatSocket
        """Segment Length"""
        segment_direction: VectorSocket
        """Segment Direction"""
        neighbor_index: IntegerSocket
        """Neighbor Index"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(self):
        super().__init__(**{})


class CurveTip(AssetGeometryGroup):
    """Curve Tip"""

    _name = "Curve Tip"
    _asset_name = "Curve Tip"
    _library = BundledLibrary("procedural_hair_node_assets.blend")

    class _Inputs(SocketAccessor):
        pass

    class _Outputs(SocketAccessor):
        tip_selection: BooleanSocket
        """Tip Selection"""
        tip_position: VectorSocket
        """Tip Position"""
        tip_direction: VectorSocket
        """Tip Direction"""
        tip_index: IntegerSocket
        """Tip Index"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(self):
        super().__init__(**{})


class CurveToTube(AssetGeometryGroup):
    """Curve to Tube"""

    _name = "Curve to Tube"
    _asset_name = "Curve to Tube"
    _library = BundledLibrary("geometry_nodes_essentials.blend")

    class _Inputs(SocketAccessor):
        curve: GeometrySocket
        """Curve"""
        scale: FloatSocket
        """Scale"""
        profile_mode: MenuSocket
        """Profile Mode"""
        profile_resolution: IntegerSocket
        """Profile Resolution"""
        shade_smooth: BooleanSocket
        """Shade Smooth"""
        resample: BooleanSocket
        """Resample"""
        resample_mode: MenuSocket
        """Resample Mode"""
        caps: BooleanSocket
        """Caps"""
        caps_type: MenuSocket
        """Caps Type"""
        caps_smooth: BooleanSocket
        """Caps Smooth"""
        uv_map: BooleanSocket
        """UV Map"""
        uv_map_name: StringSocket
        """UV Map Name"""
        uv_map_parameter_u: MenuSocket
        """UV Map Parameter U"""
        uv_map_parameter_v: MenuSocket
        """UV Map Parameter V"""

    class _Outputs(SocketAccessor):
        mesh: GeometrySocket
        """Mesh"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        curve: InputGeometry = None,
        scale: InputFloat = 0.1,
        profile_mode: InputMenu = "Round",
        profile_resolution: InputInteger = 8,
        shade_smooth: InputBoolean = True,
        resample: InputBoolean = True,
        resample_mode: InputMenu = "Evaluated",
        caps: InputBoolean = True,
        caps_type: InputMenu = "Flat",
        caps_smooth: InputBoolean = False,
        uv_map: InputBoolean = True,
        uv_map_name: InputString = "UVMap",
        uv_map_parameter_u: InputMenu = "Length",
        uv_map_parameter_v: InputMenu = "Factor",
    ):
        super().__init__(
            **{
                "Socket_0": curve,
                "Socket_5": scale,
                "Socket_4": profile_mode,
                "Socket_2": profile_resolution,
                "Socket_11": shade_smooth,
                "Socket_36": resample,
                "Socket_32": resample_mode,
                "Socket_39": caps,
                "Socket_10": caps_type,
                "Socket_15": caps_smooth,
                "Socket_31": uv_map,
                "Socket_17": uv_map_name,
                "Socket_19": uv_map_parameter_u,
                "Socket_20": uv_map_parameter_v,
            }
        )


class CustomEffector(AssetGeometryGroup):
    """Create a custom effector that can be injected into e.g. simulations."""

    _name = "Custom Effector"
    _asset_name = "Custom Effector"
    _library = BundledLibrary("geometry_nodes_dynamics_assets.blend")

    class _Inputs(SocketAccessor):
        type: MenuSocket
        """Type"""
        stage: MenuSocket
        """Stage"""
        geometry_effector: ClosureSocket
        """Geometry Effector"""
        filter: StringSocket
        """Filter"""

    class _Outputs(SocketAccessor):
        effector: BundleSocket
        """Effector"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        type: InputMenu = "Geometry",
        stage: InputMenu = "Default",
        geometry_effector: InputClosure = None,
        filter: InputString = "",
    ):
        super().__init__(
            **{
                "Socket_7": type,
                "Socket_1": stage,
                "Socket_5": geometry_effector,
                "Socket_3": filter,
            }
        )


class CustomForce(AssetGeometryGroup):
    """Create a custom force field to be used in simulations."""

    _name = "Custom Force"
    _asset_name = "Custom Force"
    _library = BundledLibrary("geometry_nodes_dynamics_assets.blend")

    class _Inputs(SocketAccessor):
        mode: MenuSocket
        """Mode"""
        selection: BooleanSocket
        """Selection"""
        force: VectorSocket
        """Force"""
        geometry_space: MenuSocket
        """Geometry Space"""
        force_space: MenuSocket
        """Force Space"""
        filter: StringSocket
        """Filter"""

    class _Outputs(SocketAccessor):
        force: BundleSocket
        """Force"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        mode: InputMenu = "Field",
        selection: InputBoolean = True,
        force: InputVector = None,
        geometry_space: InputMenu = "World Space",
        force_space: InputMenu = "World Space",
        filter: InputString = "",
    ):
        super().__init__(
            **{
                "Socket_4": mode,
                "Socket_9": selection,
                "Socket_10": force,
                "Socket_6": geometry_space,
                "Socket_7": force_space,
                "Socket_1": filter,
            }
        )


class DisplaceGeometry(AssetGeometryGroup):
    """Displace Geometry"""

    _name = "Displace Geometry"
    _asset_name = "Displace Geometry"
    _library = BundledLibrary("geometry_nodes_essentials.blend")

    class _Inputs(SocketAccessor):
        geometry: GeometrySocket
        """Geometry"""
        selection: BooleanSocket
        """Selection"""
        strength: FloatSocket
        """Strength"""
        offset_method: MenuSocket
        """Offset Method"""
        offset_distance: FloatSocket
        """Offset Distance"""
        substeps: IntegerSocket
        """Substeps"""
        post_substep_process: ClosureSocket
        """Post Substep Process"""

    class _Outputs(SocketAccessor):
        geometry: GeometrySocket
        """Geometry"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        geometry: InputGeometry = None,
        selection: InputBoolean = True,
        strength: InputFloat = 1.0,
        offset_method: InputMenu = "Normal",
        offset_distance: InputFloat = 1.0,
        substeps: InputInteger = 1,
        post_substep_process: InputClosure = None,
    ):
        super().__init__(
            **{
                "Socket_0": geometry,
                "Socket_2": selection,
                "Socket_4": strength,
                "Socket_20": offset_method,
                "Socket_6": offset_distance,
                "Socket_5": substeps,
                "Socket_19": post_substep_process,
            }
        )


class DisplaceHairCurves(AssetGeometryGroup):
    """Displace Hair Curves"""

    _name = "Displace Hair Curves"
    _asset_name = "Displace Hair Curves"
    _library = BundledLibrary("procedural_hair_node_assets.blend")

    class _Inputs(SocketAccessor):
        geometry: GeometrySocket
        """Geometry"""
        factor: FloatSocket
        """Factor"""
        shape: FloatSocket
        """Shape"""
        object_space: ObjectSocket
        """Object Space"""
        displace_vector: VectorSocket
        """Displace Vector"""
        surface_normal: BooleanSocket
        """Surface Normal"""

    class _Outputs(SocketAccessor):
        geometry: GeometrySocket
        """Geometry"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        geometry: InputGeometry = None,
        factor: InputFloat = 1.0,
        shape: InputFloat = 0.5,
        object_space: InputObject = None,
        displace_vector: InputVector = None,
        surface_normal: InputBoolean = False,
    ):
        super().__init__(
            **{
                "Input_0": geometry,
                "Input_3": factor,
                "Input_8": shape,
                "Input_2": object_space,
                "Input_9": displace_vector,
                "Socket_2": surface_normal,
            }
        )


class DuplicateHairCurves(AssetGeometryGroup):
    """Duplicate Hair Curves"""

    _name = "Duplicate Hair Curves"
    _asset_name = "Duplicate Hair Curves"
    _library = BundledLibrary("procedural_hair_node_assets.blend")

    class _Inputs(SocketAccessor):
        geometry: GeometrySocket
        """Geometry"""
        amount: IntegerSocket
        """Amount"""
        viewport_amount: FloatSocket
        """Viewport Amount"""
        radius: FloatSocket
        """Radius"""
        distribution_shape: FloatSocket
        """Distribution Shape"""
        tip_roundness: FloatSocket
        """Tip Roundness"""
        even_thickness: BooleanSocket
        """Even Thickness"""
        seed: IntegerSocket
        """Seed"""

    class _Outputs(SocketAccessor):
        geometry: GeometrySocket
        """Geometry"""
        guide_index: IntegerSocket
        """Guide Index"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        geometry: InputGeometry = None,
        amount: InputInteger = 10,
        viewport_amount: InputFloat = 1.0,
        radius: InputFloat = 0.1,
        distribution_shape: InputFloat = 0.0,
        tip_roundness: InputFloat = 0.0,
        even_thickness: InputBoolean = False,
        seed: InputInteger = 0,
    ):
        super().__init__(
            **{
                "Input_0": geometry,
                "Input_2": amount,
                "Input_4": viewport_amount,
                "Input_5": radius,
                "Input_7": distribution_shape,
                "Input_8": tip_roundness,
                "Input_6": even_thickness,
                "Input_3": seed,
            }
        )


class EdgeLength(AssetGeometryGroup):
    """Edge Length"""

    _name = "Edge Length"
    _asset_name = "Edge Length"
    _library = BundledLibrary("geometry_nodes_essentials.blend")

    class _Inputs(SocketAccessor):
        pass

    class _Outputs(SocketAccessor):
        length: FloatSocket
        """Length"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(self):
        super().__init__(**{})


class FaceCornerAngle(AssetGeometryGroup):
    """Face Corner Angle"""

    _name = "Face Corner Angle"
    _asset_name = "Face Corner Angle"
    _library = BundledLibrary("geometry_nodes_essentials.blend")

    class _Inputs(SocketAccessor):
        pass

    class _Outputs(SocketAccessor):
        corner_angle: FloatSocket
        """Corner Angle"""
        bisector: VectorSocket
        """Bisector"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(self):
        super().__init__(**{})


class FrizzHairCurves(AssetGeometryGroup):
    """Frizz Hair Curves"""

    _name = "Frizz Hair Curves"
    _asset_name = "Frizz Hair Curves"
    _library = BundledLibrary("procedural_hair_node_assets.blend")

    class _Inputs(SocketAccessor):
        geometry: GeometrySocket
        """Geometry"""
        cumulative_offset: BooleanSocket
        """Cumulative Offset"""
        factor: FloatSocket
        """Factor"""
        distance: FloatSocket
        """Distance"""
        shape: FloatSocket
        """Shape"""
        seed: IntegerSocket
        """Seed"""
        preserve_length: BooleanSocket
        """Preserve Length"""

    class _Outputs(SocketAccessor):
        geometry: GeometrySocket
        """Geometry"""
        offset_vector: VectorSocket
        """Offset Vector"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        geometry: InputGeometry = None,
        cumulative_offset: InputBoolean = True,
        factor: InputFloat = 1.0,
        distance: InputFloat = 0.01,
        shape: InputFloat = 0.5,
        seed: InputInteger = 0,
        preserve_length: InputBoolean = False,
    ):
        super().__init__(
            **{
                "Input_0": geometry,
                "Input_10": cumulative_offset,
                "Input_3": factor,
                "Input_11": distance,
                "Input_2": shape,
                "Input_8": seed,
                "Input_6": preserve_length,
            }
        )


class GenerateHairCurves(AssetGeometryGroup):
    """Generate Hair Curves"""

    _name = "Generate Hair Curves"
    _asset_name = "Generate Hair Curves"
    _library = BundledLibrary("procedural_hair_node_assets.blend")

    class _Inputs(SocketAccessor):
        hair_surface: GeometrySocket
        """Hair Surface"""
        surface_source: MenuSocket
        """Surface Source"""
        resting_surface: BooleanSocket
        """Resting Surface"""
        attach_to_surface: BooleanSocket
        """Attach to Surface"""
        hair_length: FloatSocket
        """Hair Length"""
        hair_material: MaterialSocket
        """Hair Material"""
        control_points: IntegerSocket
        """Control Points"""
        distribution_method: MenuSocket
        """Distribution Method"""
        density: FloatSocket
        """Density"""
        density_mask: FloatSocket
        """Density Mask"""
        mask_texture: ImageSocket
        """Mask Texture"""
        viewport_amount: FloatSocket
        """Viewport Amount"""
        seed: IntegerSocket
        """Seed"""

    class _Outputs(SocketAccessor):
        geometry: GeometrySocket
        """Geometry"""
        curves: GeometrySocket
        """Curves"""
        surface_normal: VectorSocket
        """Surface Normal"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        hair_surface: InputGeometry = None,
        surface_source: InputMenu = "Attached",
        resting_surface: InputBoolean = True,
        attach_to_surface: InputBoolean = True,
        hair_length: InputFloat = 1.0,
        hair_material: InputMaterial = None,
        control_points: InputInteger = 12,
        distribution_method: InputMenu = "Random",
        density: InputFloat = 10.0,
        density_mask: InputFloat = 1.0,
        mask_texture: InputImage = None,
        viewport_amount: InputFloat = 1.0,
        seed: InputInteger = 0,
    ):
        super().__init__(
            **{
                "Input_23": hair_surface,
                "Socket_3": surface_source,
                "Input_12": resting_surface,
                "Socket_2": attach_to_surface,
                "Input_20": hair_length,
                "Input_22": hair_material,
                "Input_27": control_points,
                "Socket_1": distribution_method,
                "Input_15": density,
                "Input_14": density_mask,
                "Input_19": mask_texture,
                "Input_17": viewport_amount,
                "Input_16": seed,
            }
        )


class GeometryInput(AssetGeometryGroup):
    """Geometry Input"""

    _name = "Geometry Input"
    _asset_name = "Geometry Input"
    _library = BundledLibrary("geometry_nodes_essentials.blend")

    class _Inputs(SocketAccessor):
        geometry: GeometrySocket
        """Geometry"""
        input_type: MenuSocket
        """Input Type"""
        object: ObjectSocket
        """Object"""
        relative_space: BooleanSocket
        """Relative Space"""
        as_instance: BooleanSocket
        """As Instance"""
        replace_original: BooleanSocket
        """Replace Original"""

    class _Outputs(SocketAccessor):
        geometry: GeometrySocket
        """Geometry"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        geometry: InputGeometry = None,
        input_type: InputMenu = "Object",
        object: InputObject = None,
        relative_space: InputBoolean = False,
        as_instance: InputBoolean = True,
        replace_original: InputBoolean = False,
    ):
        super().__init__(
            **{
                "Socket_7": geometry,
                "Socket_6": input_type,
                "Socket_2": object,
                "Socket_4": relative_space,
                "Socket_5": as_instance,
                "Socket_1": replace_original,
            }
        )


class GeometryPrincipalComponents(AssetGeometryGroup):
    """Principal Component Analysis (PCA) of a the positions of points"""

    _name = "Geometry Principal Components"
    _asset_name = "Geometry Principal Components"
    _library = BundledLibrary("principal_components.blend")

    class _Inputs(SocketAccessor):
        geometry: GeometrySocket
        """Geometry"""
        position: VectorSocket
        """Position"""

    class _Outputs(SocketAccessor):
        group_center: VectorSocket
        """Group Center"""
        rotation: RotationSocket
        """Rotation"""
        principal_components: VectorSocket
        """Principal Components"""
        longest_axis: VectorSocket
        """Longest Axis"""
        intermediate_axis: VectorSocket
        """Intermediate Axis"""
        shortest_axis: VectorSocket
        """Shortest Axis"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        geometry: InputGeometry = None,
        position: InputVector = None,
    ):
        super().__init__(**{"Socket_11": geometry, "Socket_0": position})


class HairCurvesNoise(AssetGeometryGroup):
    """Hair Curves Noise"""

    _name = "Hair Curves Noise"
    _asset_name = "Hair Curves Noise"
    _library = BundledLibrary("procedural_hair_node_assets.blend")

    class _Inputs(SocketAccessor):
        geometry: GeometrySocket
        """Geometry"""
        cumulative_offset: BooleanSocket
        """Cumulative Offset"""
        factor: FloatSocket
        """Factor"""
        distance: FloatSocket
        """Distance"""
        shape: FloatSocket
        """Shape"""
        scale: FloatSocket
        """Scale"""
        scale_along_curve: FloatSocket
        """Scale along Curve"""
        offset_per_curve: FloatSocket
        """Offset per Curve"""
        seed: IntegerSocket
        """Seed"""
        preserve_length: BooleanSocket
        """Preserve Length"""

    class _Outputs(SocketAccessor):
        geometry: GeometrySocket
        """Geometry"""
        offset_vector: VectorSocket
        """Offset Vector"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        geometry: InputGeometry = None,
        cumulative_offset: InputBoolean = True,
        factor: InputFloat = 1.0,
        distance: InputFloat = 0.01,
        shape: InputFloat = 0.5,
        scale: InputFloat = 1.0,
        scale_along_curve: InputFloat = 1.0,
        offset_per_curve: InputFloat = 0.0,
        seed: InputInteger = 0,
        preserve_length: InputBoolean = False,
    ):
        super().__init__(
            **{
                "Input_0": geometry,
                "Input_10": cumulative_offset,
                "Input_3": factor,
                "Input_14": distance,
                "Input_2": shape,
                "Input_11": scale,
                "Input_12": scale_along_curve,
                "Input_13": offset_per_curve,
                "Input_8": seed,
                "Input_6": preserve_length,
            }
        )


class HairDynamics(AssetGeometryGroup):
    """Simulate hair attached to a surface while taking effectors such as forces and colliders into account."""

    _name = "Hair Dynamics"
    _asset_name = "Hair Dynamics"
    _library = BundledLibrary("geometry_nodes_dynamics_assets.blend")

    class _Inputs(SocketAccessor):
        hair: GeometrySocket
        """Hair"""
        mode: MenuSocket
        """Mode"""

    class _Outputs(SocketAccessor):
        hair: GeometrySocket
        """Hair"""
        residual_error: FloatSocket
        """Residual Error"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        hair: InputGeometry = None,
        mode: InputMenu = "Animation",
    ):
        super().__init__(**{"Socket_3": hair, "Socket_44": mode})


class InstanceOnElements(AssetGeometryGroup):
    """Instance on Elements"""

    _name = "Instance on Elements"
    _asset_name = "Instance on Elements"
    _library = BundledLibrary("geometry_nodes_essentials.blend")

    class _Inputs(SocketAccessor):
        geometry: GeometrySocket
        """Geometry"""
        instance_on: MenuSocket
        """Instance On"""
        mask: FloatSocket
        """Mask"""
        input_type: MenuSocket
        """Input Type"""
        instance_type: MenuSocket
        """Instance Type"""
        object: ObjectSocket
        """Object"""
        realize_instances: BooleanSocket
        """Realize Instances"""
        keep_surface: BooleanSocket
        """Keep Surface"""
        seed: IntegerSocket
        """Seed"""
        surface_offset: FloatSocket
        """Surface Offset"""
        align_rotation: BooleanSocket
        """Align Rotation"""
        scale: VectorSocket
        """Scale"""

    class _Outputs(SocketAccessor):
        geometry: GeometrySocket
        """Geometry"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        geometry: InputGeometry = None,
        instance_on: InputMenu = "Points",
        mask: InputFloat = 1.0,
        input_type: InputMenu = "Data-Block",
        instance_type: InputMenu = "Object",
        object: InputObject = None,
        realize_instances: InputBoolean = False,
        keep_surface: InputBoolean = True,
        seed: InputInteger = 0,
        surface_offset: InputFloat = 0.0,
        align_rotation: InputBoolean = True,
        scale: InputVector = None,
    ):
        super().__init__(
            **{
                "Socket_0": geometry,
                "Socket_5": instance_on,
                "Socket_16": mask,
                "Socket_20": input_type,
                "Socket_9": instance_type,
                "Socket_2": object,
                "Socket_17": realize_instances,
                "Socket_18": keep_surface,
                "Socket_14": seed,
                "Socket_6": surface_offset,
                "Socket_7": align_rotation,
                "Socket_4": scale,
            }
        )


class InterpolateHairCurves(AssetGeometryGroup):
    """Interpolate Hair Curves"""

    _name = "Interpolate Hair Curves"
    _asset_name = "Interpolate Hair Curves"
    _library = BundledLibrary("procedural_hair_node_assets.blend")

    class _Inputs(SocketAccessor):
        geometry: GeometrySocket
        """Geometry"""
        resting_surface: BooleanSocket
        """Resting Surface"""
        follow_surface_normal: BooleanSocket
        """Follow Surface Normal"""
        part_by_mesh_islands: BooleanSocket
        """Part by Mesh Islands"""
        interpolation_guides: IntegerSocket
        """Interpolation Guides"""
        distance_to_guides: FloatSocket
        """Distance to Guides"""
        distribution_method: MenuSocket
        """Distribution Method"""
        density: FloatSocket
        """Density"""
        density_mask: FloatSocket
        """Density Mask"""
        mask_texture: ImageSocket
        """Mask Texture"""
        viewport_amount: FloatSocket
        """Viewport Amount"""
        seed: IntegerSocket
        """Seed"""

    class _Outputs(SocketAccessor):
        geometry: GeometrySocket
        """Geometry"""
        guide_index: IntegerSocket
        """Guide Index"""
        surface_normal: VectorSocket
        """Surface Normal"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        geometry: InputGeometry = None,
        resting_surface: InputBoolean = True,
        follow_surface_normal: InputBoolean = False,
        part_by_mesh_islands: InputBoolean = True,
        interpolation_guides: InputInteger = 4,
        distance_to_guides: InputFloat = 0.0,
        distribution_method: InputMenu = "Random",
        density: InputFloat = 10.0,
        density_mask: InputFloat = 1.0,
        mask_texture: InputImage = None,
        viewport_amount: InputFloat = 1.0,
        seed: InputInteger = 0,
    ):
        super().__init__(
            **{
                "Input_0": geometry,
                "Input_12": resting_surface,
                "Input_24": follow_surface_normal,
                "Input_26": part_by_mesh_islands,
                "Input_10": interpolation_guides,
                "Input_28": distance_to_guides,
                "Socket_2": distribution_method,
                "Input_15": density,
                "Input_14": density_mask,
                "Input_19": mask_texture,
                "Input_17": viewport_amount,
                "Input_16": seed,
            }
        )


class IsEdgeBoundary(AssetGeometryGroup):
    """Is Edge Boundary"""

    _name = "Is Edge Boundary"
    _asset_name = "Is Edge Boundary"
    _library = BundledLibrary("geometry_nodes_essentials.blend")

    class _Inputs(SocketAccessor):
        pass

    class _Outputs(SocketAccessor):
        is_edge_boundary: BooleanSocket
        """Is Edge Boundary"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(self):
        super().__init__(**{})


class IsEdgeLoose(AssetGeometryGroup):
    """Is Edge Loose"""

    _name = "Is Edge Loose"
    _asset_name = "Is Edge Loose"
    _library = BundledLibrary("geometry_nodes_essentials.blend")

    class _Inputs(SocketAccessor):
        pass

    class _Outputs(SocketAccessor):
        is_edge_loose: BooleanSocket
        """Is Edge Loose"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(self):
        super().__init__(**{})


class IsEdgeManifold(AssetGeometryGroup):
    """Is Edge Manifold"""

    _name = "Is Edge Manifold"
    _asset_name = "Is Edge Manifold"
    _library = BundledLibrary("geometry_nodes_essentials.blend")

    class _Inputs(SocketAccessor):
        pass

    class _Outputs(SocketAccessor):
        is_edge_manifold: BooleanSocket
        """Is Edge Manifold"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(self):
        super().__init__(**{})


class IsUVSplit(AssetGeometryGroup):
    """Is UV Split"""

    _name = "Is UV Split"
    _asset_name = "Is UV Split"
    _library = BundledLibrary("geometry_nodes_essentials.blend")

    class _Inputs(SocketAccessor):
        uv_map: VectorSocket
        """UV Map"""

    class _Outputs(SocketAccessor):
        is_uv_split: BooleanSocket
        """Is UV Split"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        uv_map: InputVector = None,
    ):
        super().__init__(**{"Socket_0": uv_map})


class NormalSelection(AssetGeometryGroup):
    """Normal Selection"""

    _name = "Normal Selection"
    _asset_name = "Normal Selection"
    _library = BundledLibrary("geometry_nodes_essentials.blend")

    class _Inputs(SocketAccessor):
        direction: VectorSocket
        """Direction"""
        threshold: FloatSocket
        """Threshold"""

    class _Outputs(SocketAccessor):
        selection: BooleanSocket
        """Selection"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        direction: InputVector = None,
        threshold: InputFloat = 0.087266,
    ):
        super().__init__(**{"Socket_1": direction, "Socket_3": threshold})


class PrincipalComponents(AssetGeometryGroup):
    """Principal Component Analysis (PCA) of a vector field"""

    _name = "Principal Components"
    _asset_name = "Principal Components"
    _library = BundledLibrary("principal_components.blend")

    class _Inputs(SocketAccessor):
        position: VectorSocket
        """Position"""
        group_id: IntegerSocket
        """Group ID"""

    class _Outputs(SocketAccessor):
        group_center: VectorSocket
        """Group Center"""
        rotation: RotationSocket
        """Rotation"""
        principal_components: VectorSocket
        """Principal Components"""
        longest_axis: VectorSocket
        """Longest Axis"""
        intermediate_axis: VectorSocket
        """Intermediate Axis"""
        shortest_axis: VectorSocket
        """Shortest Axis"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        position: InputVector = None,
        group_id: InputInteger = 0,
    ):
        super().__init__(**{"Socket_0": position, "Socket_3": group_id})


class ProjectWithDepth(AssetGeometryGroup):
    """Project with Depth"""

    _name = "Project with Depth"
    _asset_name = "Project with Depth"
    _library = BundledLibrary("geometry_nodes_essentials.blend")

    class _Inputs(SocketAccessor):
        normalized: VectorSocket
        """Normalized"""
        depth: FloatSocket
        """Depth"""
        projection: MatrixSocket
        """Projection"""
        transform: MatrixSocket
        """Transform"""
        cip_start: FloatSocket
        """Cip Start"""
        clip_end: FloatSocket
        """Clip End"""

    class _Outputs(SocketAccessor):
        vector: VectorSocket
        """Vector"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        normalized: InputVector = None,
        depth: InputFloat = 1.0,
        projection: InputMatrix = None,
        transform: InputMatrix = None,
        cip_start: InputFloat = 0.1,
        clip_end: InputFloat = 100.0,
    ):
        super().__init__(
            **{
                "Socket_3": normalized,
                "Socket_2": depth,
                "Socket_5": projection,
                "Socket_6": transform,
                "Socket_0": cip_start,
                "Socket_1": clip_end,
            }
        )


class RandomRotation(AssetGeometryGroup):
    """Random Rotation"""

    _name = "Random Rotation"
    _asset_name = "Random Rotation"
    _library = BundledLibrary("geometry_nodes_essentials.blend")

    class _Inputs(SocketAccessor):
        min_zenith: FloatSocket
        """Min Zenith"""
        max_zenith: FloatSocket
        """Max Zenith"""
        id: IntegerSocket
        """ID"""
        seed: IntegerSocket
        """Seed"""

    class _Outputs(SocketAccessor):
        rotation: RotationSocket
        """Rotation"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        min_zenith: InputFloat = 0.0,
        max_zenith: InputFloat = 3.141593,
        id: InputInteger = 0,
        seed: InputInteger = 0,
    ):
        super().__init__(
            **{
                "Socket_3": min_zenith,
                "Socket_4": max_zenith,
                "Socket_0": id,
                "Socket_1": seed,
            }
        )


class RandomizeTransforms(AssetGeometryGroup):
    """Randomize Transforms"""

    _name = "Randomize Transforms"
    _asset_name = "Randomize Transforms"
    _library = BundledLibrary("geometry_nodes_essentials.blend")

    class _Inputs(SocketAccessor):
        instances: GeometrySocket
        """Instances"""
        selection: BooleanSocket
        """Selection"""
        local_space: BooleanSocket
        """Local Space"""
        offset: VectorSocket
        """Offset"""
        rotation: VectorSocket
        """Rotation"""
        scale_axes: MenuSocket
        """Scale Axes"""
        scale: FloatSocket
        """Scale"""
        flipping: VectorSocket
        """Flipping"""
        seed: IntegerSocket
        """Seed"""

    class _Outputs(SocketAccessor):
        instances: GeometrySocket
        """Instances"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        instances: InputGeometry = None,
        selection: InputBoolean = True,
        local_space: InputBoolean = True,
        offset: InputVector = None,
        rotation: InputVector = None,
        scale_axes: InputMenu = "Uniform",
        scale: InputFloat = 0.0,
        flipping: InputVector = None,
        seed: InputInteger = 0,
    ):
        super().__init__(
            **{
                "Socket_0": instances,
                "Socket_2": selection,
                "Socket_10": local_space,
                "Socket_6": offset,
                "Socket_3": rotation,
                "Socket_7": scale_axes,
                "Socket_8": scale,
                "Socket_9": flipping,
                "Socket_5": seed,
            }
        )


class RedistributeCurvePoints(AssetGeometryGroup):
    """Redistribute Curve Points"""

    _name = "Redistribute Curve Points"
    _asset_name = "Redistribute Curve Points"
    _library = BundledLibrary("procedural_hair_node_assets.blend")

    class _Inputs(SocketAccessor):
        curves: GeometrySocket
        """Curves"""
        factor: FloatSocket
        """Factor"""
        feature_awareness: BooleanSocket
        """Feature Awareness"""

    class _Outputs(SocketAccessor):
        curves: GeometrySocket
        """Curves"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        curves: InputGeometry = None,
        factor: InputFloat = 1.0,
        feature_awareness: InputBoolean = False,
    ):
        super().__init__(
            **{"Input_0": curves, "Input_2": factor, "Input_3": feature_awareness}
        )


class RestoreCurveSegmentLength(AssetGeometryGroup):
    """Restore Curve Segment Length"""

    _name = "Restore Curve Segment Length"
    _asset_name = "Restore Curve Segment Length"
    _library = BundledLibrary("procedural_hair_node_assets.blend")

    class _Inputs(SocketAccessor):
        curves: GeometrySocket
        """Curves"""
        selection: BooleanSocket
        """Selection"""
        factor: FloatSocket
        """Factor"""
        reference_position: VectorSocket
        """Reference Position"""
        pin_at_parameter: FloatSocket
        """Pin at Parameter"""

    class _Outputs(SocketAccessor):
        curves: GeometrySocket
        """Curves"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        curves: InputGeometry = None,
        selection: InputBoolean = True,
        factor: InputFloat = 1.0,
        reference_position: InputVector = None,
        pin_at_parameter: InputFloat = 0.0,
    ):
        super().__init__(
            **{
                "Input_0": curves,
                "Input_4": selection,
                "Input_3": factor,
                "Input_2": reference_position,
                "Input_6": pin_at_parameter,
            }
        )


class RollHairCurves(AssetGeometryGroup):
    """Roll Hair Curves"""

    _name = "Roll Hair Curves"
    _asset_name = "Roll Hair Curves"
    _library = BundledLibrary("procedural_hair_node_assets.blend")

    class _Inputs(SocketAccessor):
        geometry: GeometrySocket
        """Geometry"""
        factor: FloatSocket
        """Factor"""
        subdivision: IntegerSocket
        """Subdivision"""
        variation_level: IntegerSocket
        """Variation Level"""
        roll_length: FloatSocket
        """Roll Length"""
        roll_radius: FloatSocket
        """Roll Radius"""
        roll_depth: FloatSocket
        """Roll Depth"""
        roll_taper: FloatSocket
        """Roll Taper"""
        retain_overall_shape: FloatSocket
        """Retain Overall Shape"""
        roll_direction: VectorSocket
        """Roll Direction"""
        random_orientation: FloatSocket
        """Random Orientation"""
        seed: IntegerSocket
        """Seed"""
        preserve_length: BooleanSocket
        """Preserve Length"""

    class _Outputs(SocketAccessor):
        geometry: GeometrySocket
        """Geometry"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        geometry: InputGeometry = None,
        factor: InputFloat = 1.0,
        subdivision: InputInteger = 1,
        variation_level: InputInteger = 10,
        roll_length: InputFloat = 0.1,
        roll_radius: InputFloat = 0.05,
        roll_depth: InputFloat = 0.0,
        roll_taper: InputFloat = 0.0,
        retain_overall_shape: InputFloat = 0.0,
        roll_direction: InputVector = None,
        random_orientation: InputFloat = 0.5,
        seed: InputInteger = 0,
        preserve_length: InputBoolean = False,
    ):
        super().__init__(
            **{
                "Input_0": geometry,
                "Input_10": factor,
                "Input_13": subdivision,
                "Input_11": variation_level,
                "Input_2": roll_length,
                "Input_3": roll_radius,
                "Input_9": roll_depth,
                "Input_4": roll_taper,
                "Input_5": retain_overall_shape,
                "Input_7": roll_direction,
                "Input_6": random_orientation,
                "Input_8": seed,
                "Input_12": preserve_length,
            }
        )


class RotateHairCurves(AssetGeometryGroup):
    """Rotate Hair Curves"""

    _name = "Rotate Hair Curves"
    _asset_name = "Rotate Hair Curves"
    _library = BundledLibrary("procedural_hair_node_assets.blend")

    class _Inputs(SocketAccessor):
        geometry: GeometrySocket
        """Geometry"""
        factor: FloatSocket
        """Factor"""
        axis: VectorSocket
        """Axis"""
        angle: FloatSocket
        """Angle"""
        random_offset: FloatSocket
        """Random Offset"""
        lock_ends: BooleanSocket
        """Lock Ends"""
        seed: IntegerSocket
        """Seed"""

    class _Outputs(SocketAccessor):
        geometry: GeometrySocket
        """Geometry"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        geometry: InputGeometry = None,
        factor: InputFloat = 1.0,
        axis: InputVector = None,
        angle: InputFloat = 0.0,
        random_offset: InputFloat = 0.349066,
        lock_ends: InputBoolean = False,
        seed: InputInteger = 0,
    ):
        super().__init__(
            **{
                "Input_0": geometry,
                "Input_5": factor,
                "Input_3": axis,
                "Input_2": angle,
                "Input_6": random_offset,
                "Input_8": lock_ends,
                "Input_7": seed,
            }
        )


class ScatterOnSurface(AssetGeometryGroup):
    """Scatter on Surface"""

    _name = "Scatter on Surface"
    _asset_name = "Scatter on Surface"
    _library = BundledLibrary("geometry_nodes_essentials.blend")

    class _Inputs(SocketAccessor):
        mesh: GeometrySocket
        """Mesh"""
        selection: BooleanSocket
        """Selection"""
        density_method: MenuSocket
        """Density Method"""
        distribution_method: MenuSocket
        """Distribution Method"""
        density: FloatSocket
        """Density"""
        distribution_mask: FloatSocket
        """Distribution Mask"""
        keep_surface: BooleanSocket
        """Keep Surface"""
        scatter_on_instances: BooleanSocket
        """Scatter on Instances"""
        seed: IntegerSocket
        """Seed"""
        input_type: MenuSocket
        """Input Type"""
        instance_type: MenuSocket
        """Instance Type"""
        object: ObjectSocket
        """Object"""
        viewport_visibility: FloatSocket
        """Viewport Visibility"""
        realize_instances: BooleanSocket
        """Realize Instances"""
        surface_offset: FloatSocket
        """Surface Offset"""
        align_rotation: BooleanSocket
        """Align Rotation"""
        alignment_axis: MenuSocket
        """Alignment Axis"""
        scale: VectorSocket
        """Scale"""
        randomize: BooleanSocket
        """Randomize"""
        masking: BooleanSocket
        """Masking"""

    class _Outputs(SocketAccessor):
        instances: GeometrySocket
        """Instances"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        mesh: InputGeometry = None,
        selection: InputBoolean = True,
        density_method: InputMenu = "Density",
        distribution_method: InputMenu = "Random",
        density: InputFloat = 1.0,
        distribution_mask: InputFloat = 1.0,
        keep_surface: InputBoolean = True,
        scatter_on_instances: InputBoolean = False,
        seed: InputInteger = 0,
        input_type: InputMenu = "Data-Block",
        instance_type: InputMenu = "Object",
        object: InputObject = None,
        viewport_visibility: InputFloat = 1.0,
        realize_instances: InputBoolean = False,
        surface_offset: InputFloat = 0.0,
        align_rotation: InputBoolean = True,
        alignment_axis: InputMenu = "Z",
        scale: InputVector = None,
        randomize: InputBoolean = False,
        masking: InputBoolean = False,
    ):
        super().__init__(
            **{
                "Socket_0": mesh,
                "Socket_1": selection,
                "Socket_30": density_method,
                "Socket_12": distribution_method,
                "Socket_27": density,
                "Socket_2": distribution_mask,
                "Socket_25": keep_surface,
                "Socket_46": scatter_on_instances,
                "Socket_4": seed,
                "Socket_19": input_type,
                "Socket_6": instance_type,
                "Socket_8": object,
                "Socket_33": viewport_visibility,
                "Socket_26": realize_instances,
                "Socket_44": surface_offset,
                "Socket_18": align_rotation,
                "Socket_34": alignment_axis,
                "Socket_5": scale,
                "Socket_39": randomize,
                "Socket_29": masking,
            }
        )


class ScreenTo3DSpace(AssetGeometryGroup):
    """Screen to 3D Space"""

    _name = "Screen to 3D Space"
    _asset_name = "Screen to 3D Space"
    _library = BundledLibrary("geometry_nodes_essentials.blend")

    class _Inputs(SocketAccessor):
        normalized: VectorSocket
        """Normalized"""
        depth: FloatSocket
        """Depth"""
        camera: ObjectSocket
        """Camera"""

    class _Outputs(SocketAccessor):
        vector: VectorSocket
        """Vector"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        normalized: InputVector = None,
        depth: InputFloat = 0.5,
        camera: InputObject = None,
    ):
        super().__init__(
            **{"Socket_1": normalized, "Socket_2": depth, "Socket_0": camera}
        )


class SeparateCylindrical(AssetGeometryGroup):
    """Separate Cylindrical"""

    _name = "Separate Cylindrical"
    _asset_name = "Separate Cylindrical"
    _library = BundledLibrary("geometry_nodes_essentials.blend")

    class _Inputs(SocketAccessor):
        vector: VectorSocket
        """Vector"""

    class _Outputs(SocketAccessor):
        r: FloatSocket
        """R"""
        phi: FloatSocket
        """Phi"""
        z: FloatSocket
        """Z"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        vector: InputVector = None,
    ):
        super().__init__(**{"Input_7": vector})


class SeparateSpherical(AssetGeometryGroup):
    """Separate Spherical"""

    _name = "Separate Spherical"
    _asset_name = "Separate Spherical"
    _library = BundledLibrary("geometry_nodes_essentials.blend")

    class _Inputs(SocketAccessor):
        vector: VectorSocket
        """Vector"""

    class _Outputs(SocketAccessor):
        r: FloatSocket
        """R"""
        phi: FloatSocket
        """Phi"""
        theta: FloatSocket
        """Theta"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        vector: InputVector = None,
    ):
        super().__init__(**{"Input_7": vector})


class SetAttachmentSurface(AssetGeometryGroup):
    """Set Attachment Surface"""

    _name = "Set Attachment Surface"
    _asset_name = "Set Attachment Surface"
    _library = BundledLibrary("procedural_hair_node_assets.blend")

    class _Inputs(SocketAccessor):
        geometry: GeometrySocket
        """Geometry"""
        mode: MenuSocket
        """Mode"""
        surface_object: ObjectSocket
        """Surface Object"""
        surface_uv_map: VectorSocket
        """Surface UV Map"""

    class _Outputs(SocketAccessor):
        geometry: GeometrySocket
        """Geometry"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        geometry: InputGeometry = None,
        mode: InputMenu = "Object",
        surface_object: InputObject = None,
        surface_uv_map: InputVector = None,
    ):
        super().__init__(
            **{
                "Socket_0": geometry,
                "Socket_6": mode,
                "Socket_4": surface_object,
                "Socket_5": surface_uv_map,
            }
        )


class SetEffector(AssetGeometryGroup):
    """Add effector information to the geometry bundle."""

    _name = "Set Effector"
    _asset_name = "Set Effector"
    _library = BundledLibrary("geometry_nodes_dynamics_assets.blend")

    class _Inputs(SocketAccessor):
        geometry: GeometrySocket
        """Geometry"""
        effector: BundleSocket
        """Effector"""
        name: StringSocket
        """Name"""

    class _Outputs(SocketAccessor):
        geometry: GeometrySocket
        """Geometry"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        geometry: InputGeometry = None,
        effector: InputBundle = None,
        name: InputString = "",
    ):
        super().__init__(
            **{"Socket_2": geometry, "Socket_0": effector, "Socket_3": name}
        )


class SetHairCurveProfile(AssetGeometryGroup):
    """Set Hair Curve Profile"""

    _name = "Set Hair Curve Profile"
    _asset_name = "Set Hair Curve Profile"
    _library = BundledLibrary("procedural_hair_node_assets.blend")

    class _Inputs(SocketAccessor):
        geometry: GeometrySocket
        """Geometry"""
        replace_radius: BooleanSocket
        """Replace Radius"""
        radius: FloatSocket
        """Radius"""
        shape: FloatSocket
        """Shape"""
        factor_min: FloatSocket
        """Factor Min"""
        factor_max: FloatSocket
        """Factor Max"""

    class _Outputs(SocketAccessor):
        geometry: GeometrySocket
        """Geometry"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        geometry: InputGeometry = None,
        replace_radius: InputBoolean = True,
        radius: InputFloat = 0.01,
        shape: InputFloat = 0.5,
        factor_min: InputFloat = 0.0,
        factor_max: InputFloat = 1.0,
    ):
        super().__init__(
            **{
                "Input_0": geometry,
                "Input_6": replace_radius,
                "Input_3": radius,
                "Input_2": shape,
                "Input_4": factor_min,
                "Input_5": factor_max,
            }
        )


class ShrinkwrapHairCurves(AssetGeometryGroup):
    """Shrinkwrap Hair Curves"""

    _name = "Shrinkwrap Hair Curves"
    _asset_name = "Shrinkwrap Hair Curves"
    _library = BundledLibrary("procedural_hair_node_assets.blend")

    class _Inputs(SocketAccessor):
        geometry: GeometrySocket
        """Geometry"""
        surface_input_type: MenuSocket
        """Surface Input Type"""
        surface: ObjectSocket
        """Surface"""
        factor: FloatSocket
        """Factor"""
        offset_distance: FloatSocket
        """Offset Distance"""
        above_surface: FloatSocket
        """Above Surface"""
        smoothing_steps: IntegerSocket
        """Smoothing Steps"""
        lock_roots: BooleanSocket
        """Lock Roots"""

    class _Outputs(SocketAccessor):
        geometry: GeometrySocket
        """Geometry"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        geometry: InputGeometry = None,
        surface_input_type: InputMenu = "Object",
        surface: InputObject = None,
        factor: InputFloat = 1.0,
        offset_distance: InputFloat = 0.0,
        above_surface: InputFloat = 0.5,
        smoothing_steps: InputInteger = 0,
        lock_roots: InputBoolean = True,
    ):
        super().__init__(
            **{
                "Input_0": geometry,
                "Socket_0": surface_input_type,
                "Input_2": surface,
                "Input_5": factor,
                "Input_4": offset_distance,
                "Input_8": above_surface,
                "Input_6": smoothing_steps,
                "Input_7": lock_roots,
            }
        )


class SmoothByAngle(AssetGeometryGroup):
    """Smooth by Angle"""

    _name = "Smooth by Angle"
    _asset_name = "Smooth by Angle"
    _library = BundledLibrary("geometry_nodes_essentials.blend")

    class _Inputs(SocketAccessor):
        mesh: GeometrySocket
        """Mesh"""
        angle: FloatSocket
        """Angle"""
        ignore_sharpness: BooleanSocket
        """Ignore Sharpness"""

    class _Outputs(SocketAccessor):
        mesh: GeometrySocket
        """Mesh"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        mesh: InputGeometry = None,
        angle: InputFloat = 0.523599,
        ignore_sharpness: InputBoolean = False,
    ):
        super().__init__(
            **{"Input_0": mesh, "Input_1": angle, "Socket_1": ignore_sharpness}
        )


class SmoothGeometry(AssetGeometryGroup):
    """Smooth Geometry"""

    _name = "Smooth Geometry"
    _asset_name = "Smooth Geometry"
    _library = BundledLibrary("geometry_nodes_essentials.blend")

    class _Inputs(SocketAccessor):
        geometry: GeometrySocket
        """Geometry"""
        selection: BooleanSocket
        """Selection"""
        iterations: IntegerSocket
        """Iterations"""
        weight: FloatSocket
        """Weight"""

    class _Outputs(SocketAccessor):
        geometry: GeometrySocket
        """Geometry"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        geometry: InputGeometry = None,
        selection: InputBoolean = True,
        iterations: InputInteger = 5,
        weight: InputFloat = 0.5,
    ):
        super().__init__(
            **{
                "Socket_0": geometry,
                "Socket_2": selection,
                "Socket_3": iterations,
                "Socket_4": weight,
            }
        )


class SmoothHairCurves(AssetGeometryGroup):
    """Smooth Hair Curves"""

    _name = "Smooth Hair Curves"
    _asset_name = "Smooth Hair Curves"
    _library = BundledLibrary("procedural_hair_node_assets.blend")

    class _Inputs(SocketAccessor):
        geometry: GeometrySocket
        """Geometry"""
        amount: FloatSocket
        """Amount"""
        shape: FloatSocket
        """Shape"""
        iterations: IntegerSocket
        """Iterations"""
        weight: FloatSocket
        """Weight"""
        lock_tips: BooleanSocket
        """Lock Tips"""
        preserve_length: BooleanSocket
        """Preserve Length"""

    class _Outputs(SocketAccessor):
        geometry: GeometrySocket
        """Geometry"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        geometry: InputGeometry = None,
        amount: InputFloat = 1.0,
        shape: InputFloat = 0.0,
        iterations: InputInteger = 10,
        weight: InputFloat = 0.5,
        lock_tips: InputBoolean = False,
        preserve_length: InputBoolean = True,
    ):
        super().__init__(
            **{
                "Input_0": geometry,
                "Input_10": amount,
                "Input_13": shape,
                "Input_3": iterations,
                "Input_4": weight,
                "Input_2": lock_tips,
                "Input_8": preserve_length,
            }
        )


class SphereSelection(AssetGeometryGroup):
    """Sphere Selection"""

    _name = "Sphere Selection"
    _asset_name = "Sphere Selection"
    _library = BundledLibrary("geometry_nodes_essentials.blend")

    class _Inputs(SocketAccessor):
        center: VectorSocket
        """Center"""
        radius: FloatSocket
        """Radius"""

    class _Outputs(SocketAccessor):
        selection: BooleanSocket
        """Selection"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        center: InputVector = None,
        radius: InputFloat = 1.0,
    ):
        super().__init__(**{"Socket_1": center, "Socket_2": radius})


class StraightenHairCurves(AssetGeometryGroup):
    """Straighten Hair Curves"""

    _name = "Straighten Hair Curves"
    _asset_name = "Straighten Hair Curves"
    _library = BundledLibrary("procedural_hair_node_assets.blend")

    class _Inputs(SocketAccessor):
        geometry: GeometrySocket
        """Geometry"""
        amount: FloatSocket
        """Amount"""
        shape: FloatSocket
        """Shape"""
        preserve_length: BooleanSocket
        """Preserve Length"""

    class _Outputs(SocketAccessor):
        geometry: GeometrySocket
        """Geometry"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        geometry: InputGeometry = None,
        amount: InputFloat = 1.0,
        shape: InputFloat = 0.0,
        preserve_length: InputBoolean = True,
    ):
        super().__init__(
            **{
                "Input_0": geometry,
                "Input_2": amount,
                "Input_9": shape,
                "Input_7": preserve_length,
            }
        )


class TransformAndProject(AssetGeometryGroup):
    """Transform and Project"""

    _name = "Transform and Project"
    _asset_name = "Transform and Project"
    _library = BundledLibrary("geometry_nodes_essentials.blend")

    class _Inputs(SocketAccessor):
        vector: VectorSocket
        """Vector"""
        transform: MatrixSocket
        """Transform"""
        projection: MatrixSocket
        """Projection"""

    class _Outputs(SocketAccessor):
        normalized: VectorSocket
        """Normalized"""
        depth: FloatSocket
        """Depth"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        vector: InputVector = None,
        transform: InputMatrix = None,
        projection: InputMatrix = None,
    ):
        super().__init__(
            **{"Socket_0": vector, "Socket_1": transform, "Socket_2": projection}
        )


class TrimHairCurves(AssetGeometryGroup):
    """Trim Hair Curves"""

    _name = "Trim Hair Curves"
    _asset_name = "Trim Hair Curves"
    _library = BundledLibrary("procedural_hair_node_assets.blend")

    class _Inputs(SocketAccessor):
        geometry: GeometrySocket
        """Geometry"""
        scale_uniform: BooleanSocket
        """Scale Uniform"""
        length_factor: FloatSocket
        """Length Factor"""
        replace_length: BooleanSocket
        """Replace Length"""
        length: FloatSocket
        """Length"""
        mask: FloatSocket
        """Mask"""
        random_offset: FloatSocket
        """Random Offset"""
        pin_at_parameter: FloatSocket
        """Pin at Parameter"""
        seed: IntegerSocket
        """Seed"""

    class _Outputs(SocketAccessor):
        geometry: GeometrySocket
        """Geometry"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        geometry: InputGeometry = None,
        scale_uniform: InputBoolean = False,
        length_factor: InputFloat = 1.0,
        replace_length: InputBoolean = True,
        length: InputFloat = 1.0,
        mask: InputFloat = 1.0,
        random_offset: InputFloat = 0.0,
        pin_at_parameter: InputFloat = 0.0,
        seed: InputInteger = 0,
    ):
        super().__init__(
            **{
                "Input_0": geometry,
                "Input_9": scale_uniform,
                "Input_5": length_factor,
                "Input_6": replace_length,
                "Input_2": length,
                "Input_7": mask,
                "Input_4": random_offset,
                "Input_3": pin_at_parameter,
                "Input_8": seed,
            }
        )


class _3DToScreenSpace(AssetGeometryGroup):
    """3D to Screen Space"""

    _name = "3D to Screen Space"
    _asset_name = "3D to Screen Space"
    _library = BundledLibrary("geometry_nodes_essentials.blend")

    class _Inputs(SocketAccessor):
        vector: VectorSocket
        """Vector"""
        camera: ObjectSocket
        """Camera"""
        clamp_depth: BooleanSocket
        """Clamp Depth"""

    class _Outputs(SocketAccessor):
        normalized: VectorSocket
        """Normalized"""
        depth: FloatSocket
        """Depth"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        vector: InputVector = None,
        camera: InputObject = None,
        clamp_depth: InputBoolean = True,
    ):
        super().__init__(
            **{"Socket_3": vector, "Socket_0": camera, "Socket_4": clamp_depth}
        )


__all__ = (
    "Array",
    "AttachHairCurvesToSurface",
    "AttachmentInfo",
    "BlendHairCurves",
    "BoxSelection",
    "BraidHairCurves",
    "CaptureRestGeometry",
    "ClothDynamicsExperimental",
    "ClumpHairCurves",
    "Collider",
    "CombineCylindrical",
    "CombineSpherical",
    "CreateGuideIndexMap",
    "CurlHairCurves",
    "CurveInfo",
    "CurveRoot",
    "CurveSegment",
    "CurveTip",
    "CurveToTube",
    "CustomEffector",
    "CustomForce",
    "DisplaceGeometry",
    "DisplaceHairCurves",
    "DuplicateHairCurves",
    "EdgeLength",
    "FaceCornerAngle",
    "FrizzHairCurves",
    "GenerateHairCurves",
    "GeometryInput",
    "GeometryPrincipalComponents",
    "HairCurvesNoise",
    "HairDynamics",
    "InstanceOnElements",
    "InterpolateHairCurves",
    "IsEdgeBoundary",
    "IsEdgeLoose",
    "IsEdgeManifold",
    "IsUVSplit",
    "NormalSelection",
    "PrincipalComponents",
    "ProjectWithDepth",
    "RandomRotation",
    "RandomizeTransforms",
    "RedistributeCurvePoints",
    "RestoreCurveSegmentLength",
    "RollHairCurves",
    "RotateHairCurves",
    "ScatterOnSurface",
    "ScreenTo3DSpace",
    "SeparateCylindrical",
    "SeparateSpherical",
    "SetAttachmentSurface",
    "SetEffector",
    "SetHairCurveProfile",
    "ShrinkwrapHairCurves",
    "SmoothByAngle",
    "SmoothGeometry",
    "SmoothHairCurves",
    "SphereSelection",
    "StraightenHairCurves",
    "TransformAndProject",
    "TrimHairCurves",
    "_3DToScreenSpace",
)
